server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_authentication
    username: root
    password: 123
  jpa:
    show-sql: false
    generate-ddl: true
